Yekan = int(input('Please enter Yekan:'))
Dahgan = int(input('Please enter dahgan:'))
Sadgan = int(input('Please enter sadgan:'))
Hezargan = int(input('Please enter hezargan:'))
Ashar = int(input('please enter ashar:'))
print(Hezargan,Sadgan,Dahgan,Yekan,".",Ashar)
