Name1 = str(input("Please write name:"))
Name2 = str(input("Please write name:"))
Name3 = str(input("Please write name:"))
Name4 = str(input("Please write name:"))
Name5 = str(input("Please write name:"))
Name6 = str(input("Please write name:"))
Name7 = str(input("Please write name:"))
Name8 = str(input("Please write name:"))
Name9 = str(input("Please write name:"))
Name10 = str(input("Please write name:"))
Special_Name = str(input("Please write the name:"))

Name1 = Name1.title()
Name2 = Name2.title()
Name3 = Name3.title()
Name4 = Name4.title()
Name5 = Name5.title()
Name6 = Name6.title()
Name7 = Name7.title()
Name8 = Name8.title()
Name9 = Name9.title()
Name10 = Name10.title()
Special_Name = Special_Name.title()

print(Name1 , Name2 , Name3 , Name4 , Name5 , Name6 , Name7 , Name8 , Name9 , Name10)
z = Special_Name.count(Special_Name)
print(z)